string_fav = input("Please enter the name of your favourite restaurant:")
int_fav = int(input("Please enter your favourite number:"))
print(string_fav)
print(int_fav)
#print(int(string_fav))
#invalid literal for int()