number1 = int(input("Please enter an integer:"))
number2 = int(input("Please enter another integer:"))
number3 = int(input("Please enter one final integer:"))
print(number1 + number2 + number3)
print(number1 - number2)
print(number1 * number3)
print((number1 + number2 + number3)/number3)